<?php
include_once (FUSION::getRoot()).DS.'class/clients.php';

$database = new Database();
$clientsArr = array();
$itemCounts = 0;

if( $database->getConnection() ) {
    $db = $database->getConnection();
    $links = new clients($db);
    $stmt = $links->getClients();
    $itemCounts = $stmt->rowCount();

    if( $itemCounts > 0 ) {
        $clientsArr["body"] = array();
        while ($row = $stmt->fetch(PDO::FETCH_ASSOC)) {
            extract($row);
            $e = array(
                "id"   => $id,
                "name" => $name
            );

            array_push($clientsArr["body"], $e);
        }//while
    }//if item counts
}//if

?>
<div>
    <?php if( sizeof($clientsArr["body"]) > 0  ) : ?>
        <div class="row" style="border-bottom: 1px solid blue">
            <div class="column">ID</div>
            <div class="column">Name</div>
        </div>
        <?php $i = 0; ?>
        <?php foreach ($clientsArr["body"] AS $memberClient) : ?>
            <?php
            $rowId = $i;
            $formId = 'editclient-form-'.$rowId;
            ?>
            <div class="row" style="padding: 2px">
                <div class="column"><?php echo $memberClient['id'] ?></div>
                <div class="column"><?php echo $memberClient['name'] ?></div>
                <div class="column">
                    <a href="#" onclick="showHideEditRow('client','<?php echo $rowId ?>')">Edit</a>
                </div>
            </div>
            <div id="edit-client-row-<?php echo $rowId ?>" class="row" style="clear: both;margin-bottom: 10px;display: none">
                <form id="<?php echo $formId ?>" method="POST" action="<?php echo $apiUrl.'/clients/edit.php' ?>">
                    <input id="<?php echo $formId."-active" ?>" type="hidden" value="0">
                    <input id="client-edit-Id-row-<?php echo $rowId ?>" type="hidden" value="<?php echo $memberClient['id'] ?>">
                    <div class="column" id="client-edit-row-result-<?php echo $rowId ?>" style="margin-top: 17px;"></div>
                    <div class="column">Name:<input id="edit-name-row-<?php echo $rowId ?>" type="text" size="10"></div>
                    <div class="column" style="margin-top: 17px;">
                        <button id="client-edit-submit-button-<?php echo $rowId ?>" onclick="editClientForm('<?php echo $rowId ?>')">
                            <span>Edit</span>
                        </button>
                    </div>
                </form>
            </div>
            <?php $i++; ?>
        <?php endforeach; ?>
        <input type="hidden" id="edit-client-item-counts" value="<?php echo $itemCounts ?>">
    <?php endif; ?>
</div>
